In [4]:
import numpy as np

In [57]:
array_1D = np.arange(10);
print(array_1D);
print('********************');
# array_1D = np.array([0,1,2,3,4,5,6,7,8,9]);
print(array_1D[2:6]);
print('********************');
print(array_1D[:3]);
print('********************');
print(array_1D[5:]);
print('********************');
print(array_1D[::2]);
print('********************');

[0 1 2 3 4 5 6 7 8 9]
********************
[2 3 4 5]
********************
[0 1 2]
********************
[5 6 7 8 9]
********************
[0 2 4 6 8]
********************


In [65]:
array_2D = np.array([[1,2,3],[4,5,6],[7,8,9]]);
print(array_2D);
print('********************');
print(array_2D[1,1]);
print('********************');
print(array_2D[:2,1:]);
print('********************');
print(array_2D[:,2]);
print('********************');

[[1 2 3]
 [4 5 6]
 [7 8 9]]
********************
5
********************
[[2 3]
 [5 6]]
********************
[3 6 9]
********************
